import "./globals.css";
import type { Metadata } from "next";
import { Lato, Poppins } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";

const lato = Lato({ subsets: ["latin"], weight: ["900"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={lato.className}>
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
